// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM6ny5Fhijy1_FAkb3cuZqoB_fLjk9J4w',
    appId: '1:421499440548:web:8762870605b119483bc531',
    messagingSenderId: '421499440548',
    projectId: 'crudapi-bc3e9',
    authDomain: 'crudapi-bc3e9.firebaseapp.com',
    storageBucket: 'crudapi-bc3e9.firebasestorage.app',
    measurementId: 'G-KKJT4MQKKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1-XaUp6wGMElqMKVsRY7SpB0SOFLwlYA',
    appId: '1:421499440548:android:6cd611f0ee818a2d3bc531',
    messagingSenderId: '421499440548',
    projectId: 'crudapi-bc3e9',
    storageBucket: 'crudapi-bc3e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvOhRCl1l0yxwU6USsmhg8ew80An4S7_8',
    appId: '1:421499440548:ios:2d5085bb0de4abb33bc531',
    messagingSenderId: '421499440548',
    projectId: 'crudapi-bc3e9',
    storageBucket: 'crudapi-bc3e9.firebasestorage.app',
    iosBundleId: 'com.example.crudLocalstorage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvOhRCl1l0yxwU6USsmhg8ew80An4S7_8',
    appId: '1:421499440548:ios:2d5085bb0de4abb33bc531',
    messagingSenderId: '421499440548',
    projectId: 'crudapi-bc3e9',
    storageBucket: 'crudapi-bc3e9.firebasestorage.app',
    iosBundleId: 'com.example.crudLocalstorage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM6ny5Fhijy1_FAkb3cuZqoB_fLjk9J4w',
    appId: '1:421499440548:web:24972844ff952c9f3bc531',
    messagingSenderId: '421499440548',
    projectId: 'crudapi-bc3e9',
    authDomain: 'crudapi-bc3e9.firebaseapp.com',
    storageBucket: 'crudapi-bc3e9.firebasestorage.app',
    measurementId: 'G-MJNY0P462R',
  );
}
